name: AntiCreep
main: com.onestian.anticreep.anticreep
version: ${project.version}
api-version: "1.13"
commands:
      acversion:
           description: Prints out plugin version.
           usage: /acversion
      acreload:
           description: reloads the config from file
           usage: /acreload
      acconfig:
           description: Edit the config from in-game
           usage: /acconfig block|player|spawn true|false