name: AntiCreep
main: com.onestian.anticreep.anticreep
version: 1.02
api-version: 1.13
commands:
      acversion:
           description: Prints out plugin version.
           usage: /acversion
      acreload:
           description: reloads the config from file
           usage: /acreload